# SPRING CONFIGURATION
spring:
  data:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inditexdb;
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

server:
  servlet:
    context-path: /api